-- Revise Entrepreneurs Schema for Series Logic

-- 1. Remove UNIQUE constraint on prefijo_letra
ALTER TABLE public.empresarios DROP CONSTRAINT IF EXISTS empresarios_prefijo_letra_key;
DROP INDEX IF EXISTS idx_empresarios_prefijo_letra; -- Drop the unique index if it exists

-- 2. Add new columns
ALTER TABLE public.empresarios 
ADD COLUMN IF NOT EXISTS consecutivo_letra INT DEFAULT 0;

ALTER TABLE public.empresarios 
ADD COLUMN IF NOT EXISTS codigo_visual TEXT;

-- 3. Add id_ean_global (as requested, generated automatically)
-- Using GENERATED BY DEFAULT AS IDENTITY so we can theoretically override if needed, but normally DB handles it.
-- This column will act as the global unique numeric identifier for EAN-13 generation later if needed.
ALTER TABLE public.empresarios 
ADD COLUMN IF NOT EXISTS id_ean_global BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 4. Re-add index for prefijo_letra (non-unique) for faster queries
CREATE INDEX IF NOT EXISTS idx_empresarios_prefijo_letra_non_unique ON public.empresarios(prefijo_letra);
